# Generated by Django 5.1.7 on 2025-04-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_remove_menuitem_category_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
